db.url=jdbc:mysql://127.0.0.1:3306/inmobiliaria_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
db.user=inmo_user
db.password=Inmo2026*
db.driver=com.mysql.cj.jdbc.Driver
